name: cat_breeds
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  retrofit: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
